version: 2
models:
 - name: dim_listings_cleansed
   description: "A cleansed version of the Airbnb listings data."
   columns:
    - name: listing_id
      description: "The unique identifier for each listing."
      data_tests:
        - unique
        - not_null
    - name: host_id
      description: "The unique identifier for each host. Links to the dim_hosts_cleansed table."
      data_tests:
        - not_null
        - relationships:
            to: ref('dim_hosts_cleansed')
            field: host_id
    - name: room_type
      data_tests:
        - not_null
        - accepted_values:
            values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
    - name: minimum_nights
      description: '{{doc("dim_listing_cleansed__minimum_nights")}}'
      data_tests:
        - not_null
        - positive_value
    - name: price
      data_tests:
        - dbt_expectations.expect_column_quantile_values_to_be_between:
            quantile: .99
            min_value: 50
            max_value: 500
        - dbt_expectations.expect_column_max_to_be_between:
            max_value: 5000
            config:
              severity: warn
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: float

 - name: dim_hosts_cleansed
   description: "A cleansed version of the Airbnb hosts data."
   columns:
    - name: host_id
      description: "The unique identifier for each host."
      data_tests:
        - unique
        - not_null
    - name: host_name
      description: "The name of the host."
      data_tests:
        - not_null
    - name: is_superhost
      description: "Indicates if the host is a superhost."
      data_tests:
        - not_null
        - accepted_values:
            values: ['t', 'f']
 - name: dim_listings_with_hosts
   tests:
   - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')

 - name: fct_reviews
   columns:
    - name: listing_id
      description: "The unique identifier for each listing. Links to the dim_listings_cleansed table."
      data_tests:
        - not_null
        - relationships:
            to: ref('dim_listings_cleansed')
            field: listing_id
